spring:
  application:
    name: notification-service
  kafka:
    topic:
      loan: loans-topic
    consumer:
      group: loan
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"

server:
  port: 0