spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/api/author/**,/author/**,/api/category/**,/category/**,/api/book/**,/book/**,/css/library.css,/js/author.js,/js/category.js,/js/book.js,/icon/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**,/customer/**,/css/customer.css,/js/customer.js,/icon/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loan/**,/loan/**,/css/loan.css,/js/loan.js,/icon/**
        - id: dashboard
          uri: lb://dashboard
          predicates:
            - Path=/dashboard/**,/css/dashboard.css,/icon/**
        - id: error-handler
          uri: lb://error-handler
          predicates:
            - Path=/error/**,/css/error.css,/icon/**

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
